filter:
    excluded_paths: [vendor/*, tests/*]
before_commands:
  - "composer install --dev --prefer-source"
tools:
    php_mess_detector: true
    php_cs_fixer:
        config: { level: psr2 }
    php_analyzer: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    external_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
